name: Run Regional
on: [push]
jobs:
  Tile00250045:
    runs-on: ubuntu-latest
    container:
        image: para2x/uiuc_custom_full_psims:5.0
        credentials:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        volumes:
            - ${{ github.workspace }}:/pysims/data
    steps:
      - name: 0-Force install git latest
        run: |
          apt-get install -y software-properties-common \
          && apt-get update \
          && add-apt-repository -y ppa:git-core/ppa \
          && apt-get update \
          && apt-get install -y git

      - name: 0.0-print info
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE

      - name: 1-Checkout our current branch
        uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}

      - name: 2-Checkout the latest data inputs
        uses: actions/checkout@main
        with:
          repository: FarmerAssist/ModelInputs
          path: Data
          ref: Tile00250045

      - name: 3-Checkout the latest simulation
        uses: actions/checkout@v2
        with:
          repository: FarmerAssist/Simulation
          path: Sims

      - name: 4-Checkout the latest pSIMS
        uses: actions/checkout@v2
        with:
          repository: AgronomicForecastingLab/pysims
          token: ${{ secrets.GITHUBTOKEN }}
          path: pysims

      - name: 5-Run the model
        run: |
          bash /pysims/data/Sims/Champaign/test_apsim_TL.sh '0025' '0045'

      - name: 6.0-Cleaning dirs
        run: |
          rm -r /pysims/data/Data /pysims/data/Sims /pysims/data/pysims

      - name: 6.1-Cleaning files nc
        run: |
          find /pysims/data -name "*.nc*" -type f -delete

      - name: 6.2-Cleaning files tar
        run: |
          find /pysims/data -name "*.tar*" -type f -delete

      - name: 6.3-Cleaning files sims
        run: |
          find /pysims/data -name "*.sim" -type f -delete

      - name: 6.4-Cleaning files sums
        run: |
          find /pysims/data -name "*.sum" -type f -delete

      - name: 6.5-Cleaning files met
        run: |
          find /pysims/data -name "*.met" -type f -delete

      - name: 6.6-Cleaning files old apsim files
        run: |
          find /pysims/data -name "*.old" -type f -delete

      - name: Change Owner of Container Working Directory
        run: chown root:root .

      - name: 8-Commit the model outputs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "A new round of simulations"
          repository: /pysims/data/
          commit_options: '--no-verify --signoff'
          push_options: '--force'
          status_options: '--untracked-files=no'
          skip_dirty_check: true
          create_branch: true
          branch: Tile00250045
